### ISSUE TITLE
how to fix this error?

### ISSUE THREAD

**Issue by FIXERMAN** [enemy-submarine/pidrila#2]
sudo python3 pidrila.py -u https://www.site.com/
Traceback (most recent call last):
  File "pidrila.py", line 17, in <module>
    from lib import Config, Controller
  File "/home/fixer/tools/pidrila/lib/__init__.py", line 20, in <module>
    from .controller import *
  File "/home/fixer/tools/pidrila/lib/controller.py", line 22, in <module>
    from lib.scan_manager import ScanManager
  File "/home/fixer/tools/pidrila/lib/scan_manager.py", line 21, in <module>
    from aiohttp import ClientSession, ClientTimeout, TCPConnector, client_exceptions
ModuleNotFoundError: No module named 'aiohttp'

**Comment by FIXERMAN** [comment]
pip3 install aiohttp
sorry))

**Comment by FIXERMAN** [comment]
how can you work with the list of URL domains?

**Comment by ASFH** [comment]
According to PIDRILA options, you should use option -L with a filename which contains a list of URL domains
